#!/usr/bin/env sh

. "$(dirname "$0")/lib/functions.sh"

current_branch=$(git symbolic-ref --short HEAD)
base_branch=$(get_base_branch)
repo_root="$(git rev-parse --show-toplevel)"

# Only run on backend directory.
if ! git diff --quiet "$base_branch" "$current_branch"; then
  cd "$repo_root" || exit 1 
  bun run type-check
  bun run lint
fi
